version: '3.9'
services:
  db: 
    container_name: pdp_db_1
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: danylo
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}